sap.ui.define(
    [],
    function () {
        "use strict";
        return {
            MODEL: {
                viewModel: "viewModel",
                listItemsModel: "listItemsModel",
                detailModel: "detailModel",
                approvalModel: "approvalModel",
                i18n: "i18n",
                toolsModel: "toolsModel",
                comboBoxCurrencyModel: "comboBoxCurrencyModel",
            },
            LAYOUT: {
                ThreeColumnsEndExpanded: "ThreeColumnsEndExpanded",
                TwoColumnsMidExpanded: "TwoColumnsMidExpanded",
            },
            ROUTES: {
                detail: "detail",
                approval: "approval",
                fragments: {
                    sortDialog: "zerotouchccms.zerotouchcashapplicationinbox.fragments.SortDialog",
                    filterDialog: "demowdi5.demowdi5.fragments.FilterDialog",
                    calendarDialog: "zerotouchccms.zerotouchcashapplicationinbox.fragments.CalendarPopUp",
                    sortDialogItems: "zerotouchccms.zerotouchcashapplicationinbox.fragments.SortDialogItems",
                },
                proyect: "zerotouchccms.zerotouchcashapplicationinbox",
            },
            PROPERTIES: {
                layout: "/layout",
                userName: "userName",
                billingRequestorName: "/BillingRequestorName",
                idInstruction: "/IdInstruction",
                idInvoice: "/IdInvoice",
                companyCode: "/Companycode",
                businessPartnerName: "/businessPartnerName",
                localLastChangedAt: "/Locallastchangedat",
                comments: "/Comments",
                toItem: "/to_item",
                countItems: "/itemsCount",
                instructionCount: "/instructionCount",
                infoToolbarVisible: "/infoToolbarVisible",
                totalListItems: "/totalListItems",
                toItem: "/to_item",
                idStatus: "/IdStatus",
                notificationStatus: "/notificationStatus",
            },
            FILES: {
                dataJson: "data.json",
            },
            STATE: {
                disable: "disable",
                enable: "enable",
            },
            IDS: {
                fragments: {
                    itemDetails: "idFragmentItemDetails",
                    calendarPopup: "CalendarPopup",
                },
                editBtn: "idBtnEdit",
                checkDebit: "idCheckDebit",
                checkCredit: "idCheckCredit",
                inpAllocatedAmount: "idInpAllocatedAmount",
                inpCurrency: "idInpCurrency",
                inpGLAccount: "idInpGLAccount",
                inpPostingDate: "idInpPostingDate",
                list: "idList",
                calendar: "idCalendar",
                detailTable: "idDetailTable",
            },
            BUTTONS: {
                btnTooltipEdit: "btnTooltipEdit",
                btnTooltipSave: "btnTooltipSave",
            },
            FILTERFIELDS: {
                fIdInstruction: "IdInstruction",
                fCompanyCode: "Companycode",
                fBillingRequestor: "BillingRequestorName",
                fBusinessPartnerName: "businessPartnerName",
                fLocallastchangedat: "Locallastchangedat",

                fTextIdIntruction: "Instruction No.",
                fTextCompanyCode: "Company Code",
                fTextBillingRequestor: "Billing Requestor Name",
                fTextBusinessPartnerName: "Business Partner Name",
            },
            VALUES: {
                datePattern: "yyyy-MM-dd",
                editIcon: "sap-icon://edit",
                saveIcon: "sap-icon://save",
                questionIcon: "sap-icon://question-mark",
                alertIcon: "sap-icon://alert",
                awaitingIcon: "sap-icon://pending",
                completeIcon: "sap-icon://status-completed",
                statWarning: "Warning",
                statError: "Error",
                statSuccess: "Success",
                statNone: "None",
                btnGhost: "Ghost",
                btnCritical: "Critical",
                btnSuccess: "Success",
                btnNegative: "Negative",
                btnEmphasized: "Emphasized",
                btnAccept: "Accept",
                btnAttention: "Attention",
                btnNegative: "Negative",
                iconFlag: "sap-icon://flag",
                iconPending: "sap-icon://alert",
                iconApprove: "sap-icon://message-success",
                iconRejected: "sap-icon://sys-cancel",
                iconInformation: "sap-icon://message-information",
                iconReview: "sap-icon://activity-individual",
                iconReversed: "sap-icon://undo",
                iconError: "sap-icon://cancel",
                statInformation: "Information",
            },

            BUNDLE: {
                excelName: "excelName",
                okExcel: "okExcel",
                errorExcel: "errorExcel",
                approveAction: "approveAction",
                rejectAction: "rejectAction",
                msgDoTreatmentItem: "msgDoTreatmentItem",
                msgApproveItem: "msgApproveItem",
                msgRejectItem: "msgRejectItem",
                errCheckBoxesNotSelected: "errCheckBoxesNotSelected",
                msgCanNotTreatItem: "msgCanNotTreatItem",
                tooltipNewStatus: "tooltipNewStatus",
                tooltipAwaitingStatus: "tooltipAwaitingStatus",
                tooltipCompletedStatus: "tooltipCompletedStatus",
                new: "new",
                pending: "pending",
                approved: "approved",
                rejected: "rejected",
                moreInformation: "moreInformation",
                review: "review",
                reversed: "reversed",
                paymentError: "paymentError",
                invoiceError: "invoiceError",
                awaitingReview: "awaitingReview",
                completed: "completed",
                inProgress: "inProgress",
            },

            STATE: {
                new: "1",
                pending: "2",
                approved: "3",
                rejected: "4",
                moreInformation: "5",
                review: "6",
                reversed: "7",
                paymentError: "8",
                invoiceError: "9",
            },

            SERVICE_PATH: "sap/opu/odata/sap/",

            service: {
                // ZSD_ZERO_TOUCH: "ZSB_ZEROTOUCH_V2"
                ZSD_ZERO_TOUCH: "ZSB_ZEROTOUCH",
            },

            versionado: {
                V: ";v=0003",
            },

            entity: {
                APPROVAL_ITEM: "Master",
            },

            method: {
                GET: "GET",
            },
        };
    },
    true
);
