sap.ui.define(
    [],
    function () {
        "use strict";
        return {
            DATA: [
                {
                    IdInstruction: "100203",
                    IdStatus: "1",
                    businessPartnerName: "Aguas Verdes SA.",
                    Companycode: "1100",
                    Localcreatedby: "CB9980000010",
                    BillingRequestorName: "Oliver Guillerman",
                    Locallastchangedby: "CB9980000010",
                    Locallastchangedat: "2023-01-25",
                    Lastchangedat: "2024-01-25",
                    Comments: "Comentario de cabecera",
                    to_item: [
                        {
                            IdInstruction: "100203",
                            IdInvoice: "1045940945",
                            IdStatus: "2",
                            Reference: "0110000003",
                            Companycode: "1100",
                            NetDueDate: "2023-11-20",
                            businessPartnerName: "Aguas Verdes SA.",
                            Allocatedamount: "1052877.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2023-01-20",
                            LastChangedAt: "2023-11-20",
                        },
                        {
                            IdInstruction: "100555",
                            IdInvoice: "2145922931",
                            IdStatus: "6",
                            Reference: "0110000003",
                            Companycode: "1100",
                            NetDueDate: "2023-01-12",
                            businessPartnerName: "Aguas Verdes SA.",
                            Fiscalyear: "2020",
                            Allocatedamount: "2012300.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2023-01-12",
                            LastChangedAt: "2023-01-12",
                        },
                        {
                            IdInstruction: "100002",
                            IdInvoice: "3283921940",
                            IdStatus: "3",
                            Reference: "0110000003",
                            Companycode: "1100",
                            NetDueDate: "2023-03-06",
                            businessPartnerName: "Aguas Verdes SA.",
                            Fiscalyear: "2020",
                            Allocatedamount: "4035189.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2023-01-03",
                            LastChangedAt: "2023-03-06",
                        },
                    ],
                },
                {
                    IdInstruction: "100555",
                    IdStatus: "2",
                    businessPartnerName: "Aguas Verdes SA.",
                    Companycode: "1100",
                    Localcreatedby: "CB9980000010",
                    BillingRequestorName: "Oliver Guillerman",
                    Locallastchangedby: "CB9980000010",
                    Locallastchangedat: "2022-12-28",
                    Lastchangedat: "2022-12-28",
                    Comments: "Comentario de cabecera",
                    to_item: [
                        {
                            IdInstruction: "100883",
                            IdInvoice: "2745940945",
                            IdStatus: "2",
                            Reference: "0110000003",
                            Companycode: "1100",
                            NetDueDate: "2023-03-03",
                            businessPartnerName: "Aguas Verdes SA.",
                            Fiscalyear: "2020",
                            Allocatedamount: "4852877.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2022-12-20",
                            LastChangedAt: "2023-03-03",
                        },
                        {
                            IdInstruction: "100815",
                            IdInvoice: "2745940945",
                            IdStatus: "6",
                            Reference: "0110000003",
                            Companycode: "1100",
                            NetDueDate: "2022-12-26",
                            businessPartnerName: "Aguas Verdes SA.",
                            Fiscalyear: "2020",
                            Allocatedamount: "4852877.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2022-12-26",
                            LastChangedAt: "2022-12-26",
                        },
                    ],
                },
                {
                    IdInstruction: "100025",
                    IdStatus: "4",
                    businessPartnerName: "Petroleo S.A",
                    Companycode: "1300",
                    Localcreatedby: "CB9980000010",
                    BillingRequestorName: "Charles Grace",
                    Locallastchangedby: "CB9980000010",
                    Locallastchangedat: "2022-12-30",
                    Lastchangedat: "2022-12-30",
                    Comments: "Comentario de cabecera",
                    to_item: [
                        {
                            IdInstruction: "130200",
                            IdInvoice: "2745940945",
                            IdStatus: "4",
                            Reference: "0110000003",
                            Companycode: "1300",
                            NetDueDate: "2022-11-01",
                            businessPartnerName: "Petroleo S.A",
                            Fiscalyear: "2020",
                            Allocatedamount: "4852877.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2022-11-01",
                            LastChangedAt: "2022-11-01",
                        },
                        {
                            IdInstruction: "130550",
                            IdInvoice: "2745940945",
                            IdStatus: "4",
                            Reference: "0110000003",
                            Companycode: "1300",
                            NetDueDate: "2023-03-03",
                            businessPartnerName: "Petroleo S.A",
                            Fiscalyear: "2020",
                            Allocatedamount: "4852877.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2022-11-13",
                            LastChangedAt: "2023-03-03",
                        },
                    ],
                },
                {
                    IdInstruction: "100332",
                    IdStatus: "2",
                    businessPartnerName: "Aguas S.A",
                    Companycode: "1300",
                    Localcreatedby: "CB9980000010",
                    BillingRequestorName: "Morty Smith",
                    Locallastchangedby: "CB9980000010",
                    Locallastchangedat: "2022-12-30",
                    Lastchangedat: "2022-12-30",
                    Comments: "Comentario de cabecera",
                    to_item: [
                        {
                            IdInstruction: "100203",
                            IdInvoice: "2745940945",
                            IdStatus: "5",
                            Reference: "0110000003",
                            Companycode: "1300",
                            NetDueDate: "2023-03-03",
                            businessPartnerName: "Aguas S.A",
                            Fiscalyear: "2020",
                            Allocatedamount: "4852877.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2022-11-01",
                            LastChangedAt: "2022-11-01",
                        },
                        {
                            IdInstruction: "102148",
                            IdInvoice: "2745940945",
                            IdStatus: "2",
                            Reference: "0110000003",
                            Companycode: "1300",
                            NetDueDate: "2023-03-03",
                            businessPartnerName: "Aguas S.A",
                            Fiscalyear: "2020",
                            Allocatedamount: "4852877.0",
                            Currency: "CNY",
                            Comments: "General payment instruction comment.",
                            LocalCreatedBy: "CB9980000010",
                            LocalLastChangedBy: "CB9980000010",
                            LocalLastChangedAt: "2022-11-13",
                            LastChangedAt: "2022-11-13",
                        },
                    ],
                },
            ],

            APPROVAL_ITEM: {
                CompanyCode: "1300",
                FiscalYear: "2023",
                BillingDocument: "3816066102",
                BusinessPartnerName: "Aguas Argentinas S.A.",
                BusinessPartnerID: "2869",
                NetDueDate: "27/12/2022",
                InvoiceReference: "A001-43403",
                Amount: "8039109",
                TotalDocumentAmount: "8460079",
                BPAccountID: "10760646",
                TotalLocalAmount: "9898674",
                BillingDate: "02/09/2022",
                DocumentNumber: "4400009159",
                TotalGlobalAmount: "32790844",
                OpenGlobalAmount: "7472295",
                CreditMemoGlobalAmount: "8498123",
                OpenDocumentAmount: "7932571",
                CreditMemoDocumentAmount: "5840633",
                PartialPaymentGlobalAmount: "7481485",
                PartialPaymentDocAmount: "9777951",
                AmountCurrency: "EUR",
                TotalDocumentCurrency: "USD",
                TotalLocalCurrency: "ARS",
                TOTALGlobalCurrency: "USD",
                Comments: "This is a comment left by the Billing Requestor on the Document",
                Allocatedamount: "4852877.0",
            },
        };
    },
    true
);
